FROM alpine:3.19

COPY --from=golang:1.22-alpine /usr/local/go/ /usr/local/go/

ENV PATH="/usr/local/go/bin:${PATH}"

RUN apk add --no-cache \
    git \
    gcc \
    musl-dev \
    wget \
    bash

RUN git clone https://github.com/hexahigh/yapc.git /source && \
    cd /source && \
    git checkout main && \
    git pull

WORKDIR /source/backend

ENV CGO_ENABLED=1
RUN go build -o server ./main.go

# Download the wait-for-it.sh script
RUN wget -O /wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x /wait-for-it.sh

RUN mv ./server /server
WORKDIR /
RUN rm -rf /source

ENTRYPOINT [ "bash", "/wait-for-it.sh", "mysql:3306", "-t", "60", "--", "/server", "-d", "/data", "-db:file", "/data/yapc.db" ]
