name: "Build"


on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build-backend:
        name: Build backend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.22

            - name: Build
              run: cd backend && go build -v -o backend

            - name: Print license
              run: cd backend && ./backend -l